// AutolinkedNativeModules.g.h -- contents generated by "react-native run-windows"

#include "pch.h"

#pragma once



namespace winrt::Microsoft::ReactNative
{

static void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{

}

}
